# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.risk.proto import risk_pb2 as risk__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in risk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiskEngineStub:
    """Internal-only gRPC service consumed exclusively by the Python backend.
    Handles the CPU-bound simulation work that doesn't belong in the request path
    of the web API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/wealthpilot.risk.RiskEngine/Health',
                request_serializer=risk__pb2.HealthRequest.SerializeToString,
                response_deserializer=risk__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SimulateGoalProbability = channel.unary_unary(
                '/wealthpilot.risk.RiskEngine/SimulateGoalProbability',
                request_serializer=risk__pb2.GoalSimRequest.SerializeToString,
                response_deserializer=risk__pb2.GoalSimResponse.FromString,
                _registered_method=True)
        self.ComputePortfolioRisk = channel.unary_unary(
                '/wealthpilot.risk.RiskEngine/ComputePortfolioRisk',
                request_serializer=risk__pb2.PortfolioRiskRequest.SerializeToString,
                response_deserializer=risk__pb2.PortfolioRiskResponse.FromString,
                _registered_method=True)
        self.SimulatePortfolioProjection = channel.unary_unary(
                '/wealthpilot.risk.RiskEngine/SimulatePortfolioProjection',
                request_serializer=risk__pb2.PortfolioProjectionRequest.SerializeToString,
                response_deserializer=risk__pb2.PortfolioProjectionResponse.FromString,
                _registered_method=True)
        self.ComputeDiversification = channel.unary_unary(
                '/wealthpilot.risk.RiskEngine/ComputeDiversification',
                request_serializer=risk__pb2.DiversificationRequest.SerializeToString,
                response_deserializer=risk__pb2.DiversificationResponse.FromString,
                _registered_method=True)
        self.SimulateRetirementPlan = channel.unary_unary(
                '/wealthpilot.risk.RiskEngine/SimulateRetirementPlan',
                request_serializer=risk__pb2.RetirementPlanRequest.SerializeToString,
                response_deserializer=risk__pb2.RetirementPlanResponse.FromString,
                _registered_method=True)


class RiskEngineServicer:
    """Internal-only gRPC service consumed exclusively by the Python backend.
    Handles the CPU-bound simulation work that doesn't belong in the request path
    of the web API.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateGoalProbability(self, request, context):
        """Monte Carlo probability that a goal reaches its target value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputePortfolioRisk(self, request, context):
        """Historical VaR/CVaR of a portfolio and each bucket's risk contribution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulatePortfolioProjection(self, request, context):
        """Monte Carlo projection of the whole portfolio value forward, month by month.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeDiversification(self, request, context):
        """Correlation-based diversification & concentration analysis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateRetirementPlan(self, request, context):
        """Accumulation + retirement drawdown simulated on one continuous path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=risk__pb2.HealthRequest.FromString,
                    response_serializer=risk__pb2.HealthResponse.SerializeToString,
            ),
            'SimulateGoalProbability': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateGoalProbability,
                    request_deserializer=risk__pb2.GoalSimRequest.FromString,
                    response_serializer=risk__pb2.GoalSimResponse.SerializeToString,
            ),
            'ComputePortfolioRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputePortfolioRisk,
                    request_deserializer=risk__pb2.PortfolioRiskRequest.FromString,
                    response_serializer=risk__pb2.PortfolioRiskResponse.SerializeToString,
            ),
            'SimulatePortfolioProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulatePortfolioProjection,
                    request_deserializer=risk__pb2.PortfolioProjectionRequest.FromString,
                    response_serializer=risk__pb2.PortfolioProjectionResponse.SerializeToString,
            ),
            'ComputeDiversification': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeDiversification,
                    request_deserializer=risk__pb2.DiversificationRequest.FromString,
                    response_serializer=risk__pb2.DiversificationResponse.SerializeToString,
            ),
            'SimulateRetirementPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateRetirementPlan,
                    request_deserializer=risk__pb2.RetirementPlanRequest.FromString,
                    response_serializer=risk__pb2.RetirementPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wealthpilot.risk.RiskEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wealthpilot.risk.RiskEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiskEngine:
    """Internal-only gRPC service consumed exclusively by the Python backend.
    Handles the CPU-bound simulation work that doesn't belong in the request path
    of the web API.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wealthpilot.risk.RiskEngine/Health',
            risk__pb2.HealthRequest.SerializeToString,
            risk__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateGoalProbability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wealthpilot.risk.RiskEngine/SimulateGoalProbability',
            risk__pb2.GoalSimRequest.SerializeToString,
            risk__pb2.GoalSimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputePortfolioRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wealthpilot.risk.RiskEngine/ComputePortfolioRisk',
            risk__pb2.PortfolioRiskRequest.SerializeToString,
            risk__pb2.PortfolioRiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulatePortfolioProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wealthpilot.risk.RiskEngine/SimulatePortfolioProjection',
            risk__pb2.PortfolioProjectionRequest.SerializeToString,
            risk__pb2.PortfolioProjectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeDiversification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wealthpilot.risk.RiskEngine/ComputeDiversification',
            risk__pb2.DiversificationRequest.SerializeToString,
            risk__pb2.DiversificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateRetirementPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wealthpilot.risk.RiskEngine/SimulateRetirementPlan',
            risk__pb2.RetirementPlanRequest.SerializeToString,
            risk__pb2.RetirementPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
