"""AI text providers: Anthropic API (cloud) or Ollama (the 3070 box).

Hybrid selection per docs/AI_ROADMAP.md: prefer a *reachable* Ollama for
cheap/volume tasks, fall back to the Anthropic API, else report unconfigured
so callers can degrade gracefully. Numbers are never generated by the model —
callers pass fully computed context and the model only narrates it.
"""

from __future__ import annotations

import logging
import re
from typing import Protocol

import httpx

from app.config import get_settings

logger = logging.getLogger("wealthpilot.ai")

_THINK_RE = re.compile(r"<think>.*?</think>\s*", re.DOTALL)
# The model heads the trailer many ways: "FOLLOW-UPS:", "### Follow-Up Questions:",
# "**Questions to Ask Next:**", etc. Match any, with optional markdown wrappers.
# Order matters: the longer "…UP QUESTIONS" alt must precede "…UPS?".
_FOLLOW_ANY_RE = re.compile(
    r"[#*_]*\s*"
    r"(?:FOLLOW[- ]?UP QUESTIONS?|FOLLOW[- ]?UPS?|QUESTIONS TO ASK NEXT)"
    r"\s*:?\s*[*_]*",
    re.IGNORECASE,
)
_QUESTION_SPAN_RE = re.compile(r"[^?]*\?")
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!;])\s+")
_PLACEHOLDER_RE = re.compile(r"^q\s*\d+\s*$", re.IGNORECASE)
_PLACEHOLDER_PHRASES = (
    "three short question",
    "owner would",
    "naturally ask",
    "ask next",
)


def strip_reasoning(text: str) -> str:
    """Drop <think> blocks that reasoning models (DeepSeek-R1) emit."""
    return _THINK_RE.sub("", text).strip()


def _clean_followup(candidate: str) -> str | None:
    """Normalize one follow-up candidate; None if it's placeholder/instruction text."""
    q = candidate.strip()
    # Iteratively peel leading noise until stable, so labels revealed after one
    # strip (e.g. "**Follow-up 3:**" → "Follow-up 3:**" → "") get fully removed and
    # normalization is idempotent.
    for _ in range(5):
        before = q
        q = q.lstrip("-*•—–#> ").strip()
        q = re.sub(r"^\d+[.)]\s*", "", q)  # "1. " / "2) " list markers
        # "Follow-up 3:"
        q = re.sub(r"^\**\s*follow[- ]?up\s*\d*\s*:?\**\s*", "", q, flags=re.IGNORECASE)
        # Template label: punctuation-separated ("Q3:", "q2)", "q1 | ") strips in either
        # case; a bare space-separated one ("q3 Are…") only lowercase, so a legit
        # "Q4 earnings…" quarter reference survives.
        q = re.sub(r"^[qQ]\s*\d+\s*[:.)|—–-]\s*", "", q)
        q = re.sub(r"^q\s*\d+\s+", "", q)
        if q == before:
            break
    # Keep only the last sentence (a merged "statement. Question?" → the question).
    q = _SENTENCE_SPLIT_RE.split(q)[-1].strip()
    q = q.lstrip("—–-*").strip()  # stray leading dash/asterisk left by the split
    if not q or q == "---":
        return None
    if _PLACEHOLDER_RE.match(q):
        return None
    low = q.lower()
    if any(p in low for p in _PLACEHOLDER_PHRASES):
        return None
    return q


def _extract_followups(region: str) -> list[str]:
    """Pull up to 3 real follow-up questions out of the (possibly messy) trailer."""
    out: list[str] = []
    for frag in re.split(r"[|\n]+", region):
        frag = frag.strip()
        if not frag:
            continue
        # A run-on fragment may pack several "…?" questions; split those out.
        pieces = _QUESTION_SPAN_RE.findall(frag) or [frag]
        for piece in pieces:
            cleaned = _clean_followup(piece)
            if cleaned and cleaned not in out:
                out.append(cleaned)
            if len(out) == 3:
                return out
    return out


def normalize_followups(text: str) -> str:
    """Coerce a reply into a single clean `FOLLOW-UPS: a | b | c` trailer.

    The fine-tuned model emits the trailer inconsistently — sometimes the literal
    template (`FOLLOW-UPS: q1 | q2 | q3 — three short questions …`), sometimes
    mid-line, sometimes with the real questions as run-on sentences below. Find
    the marker anywhere, drop the placeholder scaffold, and rebuild one clean
    trailing line from the real questions (or drop it entirely if none are real).
    """
    m = _FOLLOW_ANY_RE.search(text)
    if not m:
        return text.strip()

    body = text[: m.start()].rstrip().rstrip("-").rstrip()
    followups = _extract_followups(text[m.end() :])
    if not followups:
        return body
    return f"{body}\n\nFOLLOW-UPS: {' | '.join(followups)}".strip()

_OLLAMA_PROBE_TIMEOUT_S = 2.0
_COMPLETION_TIMEOUT_S = 180.0  # 14B reasoning models on the 3070 need headroom


class BaseAIProvider(Protocol):
    name: str

    async def complete(self, system: str, prompt: str) -> str: ...


class AnthropicProvider:
    """Minimal Messages API client over httpx (no SDK dependency)."""

    name = "anthropic"

    def __init__(self, api_key: str, model: str) -> None:
        self._model = model
        self._client = httpx.AsyncClient(
            base_url="https://api.anthropic.com",
            timeout=_COMPLETION_TIMEOUT_S,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
        )

    async def complete(self, system: str, prompt: str) -> str:
        resp = await self._client.post(
            "/v1/messages",
            json={
                "model": self._model,
                "max_tokens": 1024,
                "system": system,
                "messages": [{"role": "user", "content": prompt}],
            },
        )
        resp.raise_for_status()
        blocks = resp.json().get("content", [])
        return "".join(b.get("text", "") for b in blocks if b.get("type") == "text")

    async def close(self) -> None:
        await self._client.aclose()


class OllamaProvider:
    """Local model on the 3070 box via Ollama's /api/generate."""

    name = "ollama"

    def __init__(self, url: str, model: str) -> None:
        self._model = model
        self._client = httpx.AsyncClient(base_url=url, timeout=_COMPLETION_TIMEOUT_S)

    async def complete(self, system: str, prompt: str) -> str:
        resp = await self._client.post(
            "/api/generate",
            json={
                "model": self._model,
                "system": system,
                "prompt": prompt,
                "stream": False,
                "keep_alive": -1,  # stay loaded — no reload between requests
                "options": {"num_ctx": 8192},
            },
        )
        resp.raise_for_status()
        return strip_reasoning(str(resp.json().get("response", "")))

    async def close(self) -> None:
        await self._client.aclose()


async def _ollama_reachable(url: str) -> bool:
    try:
        async with httpx.AsyncClient(timeout=_OLLAMA_PROBE_TIMEOUT_S) as client:
            resp = await client.get(f"{url.rstrip('/')}/api/tags")
            return resp.status_code == 200
    except httpx.HTTPError:
        return False


async def build_ai_provider() -> BaseAIProvider | None:
    """Reachable Ollama first, then Anthropic, else None (unconfigured)."""
    settings = get_settings()
    if settings.ollama_url and await _ollama_reachable(settings.ollama_url):
        logger.info("AI provider: ollama (%s)", settings.ollama_model)
        return OllamaProvider(settings.ollama_url, settings.ollama_model)
    if settings.anthropic_api_key:
        logger.info("AI provider: anthropic (%s)", settings.ai_model)
        return AnthropicProvider(settings.anthropic_api_key, settings.ai_model)
    return None
